### ISSUE TITLE
Actividad 10 Diagrama de componentes

### ISSUE THREAD

**Issue by HECTOR-KDM02** [SistemasTecTlaxiaco/actividad-10-practica-de-arquitectura-equipo-osteas-b#1]
[ACT 10-HECTOR,JOSUE.pdf](https://github.com/user-attachments/files/18029557/ACT.10-HECTOR.JOSUE.pdf)

**Comment by williamgl3** [comment]
30 cumple con las rubricas de evalucion, bien hecho

**Comment by josealfredo79** [comment]
bien hecho y revisado..
